config/routes.rb
Rails.application.routes.draw do
  root   'users#top'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users, only: [:show, :edit, :update] do
    resources :skills, only: :index
  end

  resources :users, except: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :categories, except: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources :skills, except: [:index, :show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :skills, dependent: :destroy
  accepts_nested_attributes_for :skills, allow_destroy: true
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :skill
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :levels
  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :level, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }

  validates :name, presence: true, length: { maximum: 20 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  validates :introduction, length: { minimum: 200, maximum: 800 }, allow_nil: true

  has_many :skills, dependent: :destroy
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  # ユーザーのログインを確認する
    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインしてください"
        redirect_to login_url, status: :see_other
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to user
      flash[:success] = 'ログインしました'
    else
      flash.now[:danger] = 'メールアドレスもしくはパスワードが間違っています'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to root_url, status: :see_other
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :logged_in_user
  before_action :set_skill, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
    @skills = current_user.skills
    @modal = params[:modal]
    if params[:skill_name].present?
      @category = Category.find(params[:category_id])
      @skill_name = params[:skill_name]
      @level = params[:level]
    end
  end

  def new
    @category = Category.find(params[:category_id])
    @skill = current_user.skills.new
  end

  def create
    p = skill_params
    @skill = current_user.skills.new(skill_params)
    if @skill.save
      redirect_to action: index, **p, modal: :create
    else
      flash.now[:danger] = '習得スキルを登録できませんでした'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @categories = Category.all
    @category = Category.find(params[:category_id])
    @skills = Skill.where(user_id: current_user.id)
  end

  def update
    p = skill_params
    @skill.update(skill_params)
    redirect_to action: index, **p, modal: :update
  end

  def destroy
    @skill.destroy
    redirect_to action: index, modal: :destroy, status: :see_other
  end

  private

    def skill_params
      params.require(:skill).permit(:id, :skill_name, :level, :category_id)
    end

    def set_skill
      @skill = current_user.skills.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: :top

  def top
  end

  def show
    @user = User.find(current_user.id)
    @dataset1 = Skill.where(user_id: current_user.id, category_id: 1).map(&:level)
    @dataset2 = Skill.where(user_id: current_user.id, category_id: 2).map(&:level)
    @dataset3 = Skill.where(user_id: current_user.id, category_id: 3).map(&:level)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "自己紹介を更新しました"
      redirect_to @user
    else
      flash.now[:danger] = "自己紹介を更新できませんでした"
      render :edit, status: :unprocessable_entity
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduction, :avatar)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "My Portfolio App"
    if page_title.empty?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    cookies.delete(:user_id)
  end

  # 現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    reset_session
    @current_user = nil
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="wrapper">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-container">
    <% if logged_in? %>
      <p><%= current_user.name %>'s portfolio site</p>
    <% else %>
      <p>user name’s portfolio site</p>
    <% end %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="header-container">
    <div class="logo">
      <% if logged_in? %>
        <%= link_to "My Portfolio", user_path(current_user) %>
      <% else %>
        <%= link_to "My Portfolio", root_path %>
      <% end %>
    </div>
    <div class="header-button">
      <% if logged_in? %>
        <%= link_to "ログアウト", logout_path, data: { turbo_method: :delete } ,class: "session button" %>
    <% else %>
        <%= link_to "ログイン", login_path, class: "session button" %>
    <% end %>
    </div>
  </div>
</header>

app/views/skills/edit.html.erb
<% provide(:title, 'Edit') %>
<div class="container">
  <% @categories.each do |category| %>
    <div class="card">
      <div class="card-top">
        <div class="card-title"><%= category.category_name %></div>
        <%= link_to "スキルを追加する", new_user_category_skill_path(current_user, category), class: "nomal button" %>
      </div>
      <%= form_with model: @skill, url: user_category_skill_path do |f| %>
        <table>
          <thead>
            <tr>
              <td width="200">習得スキル</td>
              <td width="200">習得レベル</td>
              <td width="240"></td>
              <td width="240"></td>
            </tr>
          </thead>
          <tbody>
            <% @skills.each do |skill| %>
              <% if category.id.eql?(skill.category_id) %>
                <tr>
                  <td><%= skill.skill_name %></td>
                  <% if @skill.id.eql?(skill.id) %>
                    <%= f.hidden_field :category_id, value: @category.id %>
                    <%= f.hidden_field :skill_name, value: skill.skill_name %>
                    <td><%= f.number_field :level, value: skill.level, class: "form-control" %></td>
                    <td><%= f.submit "習得レベルを保存する", class: "save button" %></td>
                  <% else %>
                    <td><%= skill.level %></td>
                    <td><p class="save button">習得レベルを保存する</p></td>
                  <% end %>
                  <td><p class="delete button">スキルを削除する</p></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  <% end %>
  <div class="card-bottom"></div>
</div>

app/views/skills/index.html.erb
<% provide(:title, 'Skill') %>
<div class="container">
  <% @categories.each do |category| %>
    <div class="card">
      <div class="card-top">
        <div class="card-title">
          <%= category.category_name %>
        </div>
        <%= link_to "スキルを追加する", new_user_category_skill_path(current_user, category), class: "nomal button" %>
      </div>
      <table>
        <thead>
          <tr>
            <td width="200">習得スキル</td>
            <td width="200">習得レベル</td>
            <td width="240"></td>
            <td width="240"></td>
          </tr>
        </thead>
        <tbody>
          <% @skills.each do |skill| %>
            <% if category.id.eql?(skill.category_id) %>
              <tr>
                <td><%= skill.skill_name %></td>
                <td><%= skill.level %></td>
                <td><%= link_to "習得レベルを編集する", edit_user_category_skill_path(current_user, category, skill), class: "save button" %></td>
                <td><%= link_to "スキルを削除する", user_category_skill_path(current_user, category, skill), data: { turbo_method: :delete }, class: "delete button" %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
  <div class="card-bottom"></div>
</div>

<% if @modal.eql?("destroy") %>
  <div class="overlay"></div>
  <div class="modal">
    <div class="modal-text">
      <p><br><%= @skill_name %>の項目を削除しました！</p>
    </div>
    <div class="center-button">
      <%= link_to "スキル編集ページに戻る", user_skills_path, class: "nomal button" %></div>
    </div>
  </div>
<% end %>

<% if @modal.eql?("create") %>
  <div class="overlay"></div>
  <div class="modal">
    <div class="modal-text">
      <p><%= @category.category_name %>に<%= @skill_name %>を<br>習得レベル<%= @level %>で追加しました！</p>
    </div>
    <div class="center-button">
      <%= link_to "スキル編集ページに戻る", user_skills_path, class: "nomal button" %>
    </div>
  </div>
<% end %>

<% if @modal.eql?("update") %>
  <div class="overlay"></div>
  <div class="modal">
    <div class="modal-text">
      <p><br><%= @skill_name %>の習得レベルを保存しました！</p>
    </div>
    <div class="center-button">
      <%= link_to "スキル編集ページに戻る", user_skills_path, class: "nomal button" %>
    </div>
  </div>
<% end %>

app/views/skills/new.html.erb
<% provide(:title, 'New') %>
<div class="new-container">
  <div class="title">
    <p><%= @category.category_name %>にスキルを追加</p>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= form_with model: @skill, url: user_category_skills_path do |f| %>
        <%= f.label :skill_name, "習得スキル" %>
        <%= f.text_field :skill_name, class: 'form-control' %>
        <%= f.label :level, "習得レベル" %>
        <%= f.number_field :level, class: 'form-control' %>
        <div class="explain">
          <p>0 ~ 100 の間で選択してください</p>
        </div>
        <%= f.hidden_field :category_id, value: @category.id %>
        <%= f.hidden_field :category_name, value: @category.category_name %>
        <div class="center-button">
          <%= f.submit "追加する", class: "nomal button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<div class="introduction-container">
  <div class="title">
    <p>自己紹介を編集する</p>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= form_with model: @user do |f| %>
        <%= f.label :introduction, "自己紹介文" %>
        <%= f.text_area :introduction, class: 'form-control', rows: '5' %>
        <div class="explain">
          <p>200文字以上、800文字未満で入力してください</p>
        </div>
        <%= f.label :avatar, "アバター画像" %>
        <%= f.file_field :avatar, class: 'form-control-file', style: 'border :none' %>
        <div class="center-button">
          <%= f.submit "自己紹介を確定する", class: "nomal button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, current_user.name) %>
<div class="container">
  <div class="info">
    <div class="avatar">
      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar %>
      <% else %>
        <%= image_tag 'avatar.png' %>
      <% end %>
    </div>
    <div class="introduction">
      <div class="introduction-title">
        <p>自己紹介</p>
      </div>
      <div class="introduction-text">
        <p><%= current_user.introduction %></p>
      </div>
      <div class="introduction-button">
        <%= link_to "自己紹介を編集する", edit_user_path(current_user), class: "nomal button" %>
      </div>
    </div>
  </div>
  <div class="chart">
    <div class="chart-title">
      <p>スキルチャート</p>
    </div>
    <div class="center-button">
      <%= link_to "スキルを編集する", user_skills_path(current_user), class: "nomal button" %>
    </div>
    <canvas id="mychart-bar"></canvas>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
      const ctx = document.getElementById('mychart-bar');
      const myChart = new Chart(ctx, {
        type: 'bar',
        data: {
          labels: ['January', 'February', 'March'],
          datasets: [{
            label: 'バックエンド',
            data: <%= @dataset1 %>,
            backgroundColor: '#ffc0cb',
          }, {
            label: 'フロントエンド',
            data: <%= @dataset2 %>,
            backgroundColor: '#ffd5bf',
          }, {
            label: 'インフラ',
            data: <%= @dataset3 %>,
            backgroundColor: '#fff4bf',
          }],
        },
      });
    </script>
  </div>
</div>

app/views/users/top.html.erb
<% provide(:title, 'Top') %>
<div class="container">
  <div class="info">
    <div class="avatar">
      <%= image_tag 'avatar.png' %>
    </div>
    <div class="introduction">
      <div class="introduction-title">
        <p>自己紹介</p>
      </div>
      <div class="introduction-text-nil">
        <p>ログインして、自己紹介文と画像を登録しましょう！</p>
      </div>
    </div>
  </div>
  <div class="chart">
    <div class="chart-title">
      <p>スキルチャート</p>
    </div>
    <div class="chart-image">
      <%= image_tag 'sample_chart.png' %>
    </div>
  </div>
</div>